### ISSUE TITLE
Users seeking support

### ISSUE THREAD

**Issue by shivupa** [arm61/pylj#10]
The readme says all development discussion will take place on gitter. The docs say there is a slack channel. I couldn't sign in to the slack channel because it says I need to "Contact the workspace administrator for an invitation". 

Is all communication going to occur via gitter? If so can the read me be changed to make this clearer?

**Comment by arm61** [comment]
I have now updated the webpages to direct interested contributors to the https://github.com/arm61/pylj/blob/master/CONTRIBUTING.md only. 

Further, I have updated both the https://github.com/arm61/pylj/blob/master/CONTRIBUTING.md and https://github.com/arm61/pylj/blob/master/README.md to reflect the use of gitter as the source of all discussion about development but also linked the https://gitter.im/pylj/HELP room in the https://github.com/arm61/pylj/blob/master/README.md 

This is all in https://github.com/arm61/pylj/commit/b17af7dcd913b25857f95cc6f067b0549a51fdc1
