### ISSUE TITLE
Installation manual 

### ISSUE THREAD

**Issue by TJFord** [arm61/pylj#11]
1. I really like the idea of running a demo through Jupyter, as it is convenient to test the code directly. I tried the cloud version for molecular_dynamics but not successful. Please correct me if I did it wrong. http://35.230.133.1/notebook/notebooks/examples/molecular_dynamics.ipynb#
The error message is here:
<pre>TypeError                                 Traceback (most recent call last)
 in ()
----> 1 system = md_simulation(100, 273.15, 100, 5000, 50)
 in md_simulation(number_of_particles, temperature, box_length, number_of_steps, sample_frequency)
     16                                                                                                  system.cut_off)
     17         # Run the equations of motion integrator algorithm
---> 18         system.particles = md.velocity_verlet(system.particles, system.timestep_length, system.box_length)
     19         # Sample the thermodynamic and structural parameters of the system
     20         system = md.sample(system.particles, system.box_length, system.initial_particles, system)
TypeError: velocity_verlet() missing 1 required positional argument: 'cut_off' </pre>
2. I tried to run it on a linux computer through a terminal, it was not successful either. I followed exactly all the steps shown in README.md. I suspected I missed installing some libraries. I think it will be beneficial if a detailed installation manual can be provided.

**Comment by arm61** [comment]
1) has now been resolved and the online resource updated. so the molecular_dynamics notebook should run.

**Comment by arm61** [comment]
Regarding 2. Are you trying to run components of the library? as all visualisation functions, e.g. those in the `sample` module require Jupyter notebooks to function. Really the whole software is designed to work within the Jupyter notebooks framework to allow for the easy visualisation to work. I have updated the README.md to reflect the requirement for Jupyter notebooks in https://github.com/arm61/pylj/commit/90de7f99acdd2d5122635286527faa2875f8a8b6

**Comment by shivupa** [comment]
When two people are accessing the online jupyter notebooks are they accessing separate instances?

**Comment by shivupa** [comment]
Also have you considered [binder](https://mybinder.org/) or [colaboratory](https://research.google.com/colaboratory/faq.html)

**Comment by arm61** [comment]
I don't believe so (the delay is mentioned on the [webpages](http://pythoninchemistry.org/pylj/#examples)), the online resource is designed for quick demonstration purposes only. Currently this is running on free credit on a GCloud server and I don't really have the funds to pay for it to run more instances currently.

**Comment by arm61** [comment]
I previously had it running on a GCloud binder resource (not mybinder) however as it is only really for quick demonstration purposes currently I found it was easier to manage in its current incarnation

**Comment by shivupa** [comment]
Sorry for the delay. For the submission, the way it's set up is fine. A possible overhaul of the online part could be something to address down the line.

**Comment by shivupa** [comment]
@TJFord  are you still having trouble? Both notebooks run for me now. I'd be ok with closing this.

**Comment by TJFord** [comment]
@shivupa @arm61  I run it through http://35.230.133.1/notebook/notebooks/examples/monte_carlo.ipynb, I just try it again and found it was not working.

**Comment by shivupa** [comment]
Ok it seems like the online stuff will need updated. Locally it seems to be working correctly.

**Comment by arm61** [comment]
This has now been updated and should work (the server was not updated with the newest instance of the monte_carlo notebook)

**Comment by arm61** [comment]
I have added the guide notebook which acts as a short instruction manual for the installation of pylj and introduces some of the examples. 

Note that I have not (and don't plan to) put the long form examples on the web resource as the purpose of this resource is really to give a quick example. 

I will close this issue (but feel free to re-open if unfulfilled)
