### ISSUE TITLE
Should .so files be part of the git ignore?

### ISSUE THREAD

**Issue by shivupa** [arm61/pylj#12]
This [file](https://github.com/arm61/pylj/blob/master/pylj/comp.cpython-36m-x86_64-linux-gnu.so) is part of the distribution.

**Comment by arm61** [comment]
I am not 100 % certain but I believe that it is necessary for the .so to be present to ensure that the documentation for the comp module (the cython module) is present in the readthedocs compilation. This may not be accurate but I found that the readthedocs would not include the comp module when this file was not included.

**Comment by shivupa** [comment]
Ok. That sounds like it needs to be there.
