### ISSUE TITLE
Minor efficiency improvement

### ISSUE THREAD

**Issue by shivupa** [arm61/pylj#14]
Since this is pedagogical code, I don't think the focus should be on making things faster if it becomes unreadable. However I had one change that could make things quicker and if someone is reading the code to learn, it could start them thinking about these things when programming. 

  In `comp.cpp`, change from
  ```c++
  f = (1.635e-133 * pow(dr, -13.) - 5.834e-77 * pow(dr, -7.));
  force_arr[k] = f;
  e = (1.363e-134 * pow(dr, -12.) - 9.273e-78 * pow(dr, -6.));
  energy_arr[k] = e;
  ```
  to 
  ```c++
  inv_dr_1 = 1.0 / dr;
  inv_dr_6 = pow(inv_dr_1, 6);
  
  f = (1.635e-133 * (inv_dr_1*inv_dr_6*inv_dr_6) - 5.834e-77 * (inv_dr_1*inv_dr_6*));
  force_arr[k] = f;
  e = (1.363e-134 * (inv_dr_6*inv_dr_6)) - 9.273e-78 * (inv_dr_6));
  energy_arr[k] = e;
  ```

**Comment by arm61** [comment]
Resolved in #16 (this is a nice improvment thanks :smile: )
