### ISSUE TITLE
Example notebooks

### ISSUE THREAD

**Issue by shivupa** [arm61/pylj#21]
I liked the additional notebooks. I had a few simple fixes; nothing too difficult. Pending these changes I agree that it is ready for publication. Great job!

# ideal_gas_law/first_principles.ipynb:
  When rearranging ln(Q) add some helpful hints for students:
    Between eq 1 and 2: "Using Stirling's approximation"
    Between eq 2 and 3: "Substituting the de Broglie thermal wavelength"

# ideal_gas_law/intro_to_monte_carlo.ipynb:
  typos:
    "approxmations" -> "approximations"
    "intantenous" -> "instantaneous"
    "accoprding" -> "according"
    "enivornment" -> "environment"
    "neglible" -> "negligible"
    "implimented" -> "implemented"
    
# ideal_gas_law/intro_to_molecular_dynamics.ipynb:
  typos:
    "approxmations" -> "approximations"
    "intantenous" -> "instantaneous"
    "accoprding" -> "according"
    "enivornment" -> "environment"
    "deriviative" -> "derivative"
    
# ideal_gas_law/ideal_gas_law.ipynb:
  typos:
    "approxmations" -> "approximations"
    "intantenous" -> "instantaneous"
    "accoprding" -> "according"
    "showen" -> "shown"
    "presssure" -> "pressure"
    "disucss" -> "discuss"

# In all of the "Atomistic Simulation" cells:
  The sentence: "The use of computers in chemistry is becoming more and more commonplace with increases computational resource and more efficient and effective algorithms." sounds a bit awkward.
  Consider:  "The use of computers in chemistry is becoming more common as computers are increasing in power and the algorithms are becoming more accurate and efficient."

**Comment by arm61** [comment]
@shivupa thanks for this very thorough set of comments. Really is great and super helpful :smile:. I reckon that https://github.com/arm61/pylj/commit/2d113c218e3291e597f62b1b7fa746f4f24e37a4 should take care of them all
