### ISSUE TITLE
Buckingham energy/force don't work for arrays

### ISSUE THREAD

**Issue by sansona** [arm61/pylj#46]
In writing tests, I discovered that the Buckingham forcefield functions run into a TypeError if the dr input is not a single float (i.e [dr] or for an array of different values). 

Here's the error that comes up:
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by sansona** [comment]
The test I wrote was for under test_buckingham_energy:

b = forcefields.buckingham([2.0], [1.0, 1.0, 1.0])

This should be equivalent to the test already there, but it raises a
TypeError. Same thing is Dr is an array of different length - [2.0, 2.0].
It seems something isn't working when dr is an array

**Comment by arm61** [comment]
As mentioned on https://github.com/arm61/pylj/pull/47 the object being passed is a list but the function expects either floats or np.ndarray objects (it has been a while since I looked at this code in detail so I could be mistaken)

**Comment by arm61** [comment]
Resolved in #47 and #48
