### ISSUE TITLE
Broken characters in examples

### ISSUE THREAD

**Issue by Mi-chael** [arm61/pylj#53]
In the examples, there are several fields/code boxes which are not running, since they contain broken special characters.

1. Go to 'pylj/examples/molecular_dynamics/intro_to_molecular_dynamics.ipynb'
2. Check code box 2 and 3, for example
  or
1. pylj/examples/ideal_gas_law/ideal_gas_law.ipynb
2. Check code box 2 and 3, for example

Screenshot from the "raw" notebook:
![image](https://user-images.githubusercontent.com/79084794/114008577-abb64c00-9862-11eb-9515-ac780b65c83f.png)

Checked on Ubuntu 20.04.2 LTS with
- Firefox (87.0+build3-0ubuntu0.20.04.2)
- Chromium (89.0.4389.114)

**Comment by arm61** [comment]
Hey! Thanks for the interest in pylj.

These are not broken, the idea is that you put in code yourself (so that the examples are interactive). Note, that above cell 2 of  intro_to_molecular_dynamics.ipynb there is the following text: 
> In the cell below, write a function to calculate the energy of an interaction between two argon atoms for given range of distances using the Lennard-Jones function as the model.
Indicating that you should add your own code.

**Comment by Mi-chael** [comment]
Ui, reading helps. Thanks!
