### ISSUE TITLE
status of this project

### ISSUE THREAD

**Issue by markgalassi** [arm61/pylj#61]
Dear maintainers,

I have been pointing students to this repository, but it appears to have had no work done for some 5 years, and there seem to be some problems currently.

Is there a new project with this scope?  Is there any intention of revitalizing it?

**Comment by arm61** [comment]
Thanks for getting in touch. This package was a side project during my PhD studies that lost priority when I finished. This led to the drop in development. 

However, as you note, @maximillian-dolan has started working to develop it as part of a Master’s project. The first aim will be improving sustainability of the package to make it easier for me to keep it going in future. 

If you have any feature requests or notice bugs please open an issue as usual and we can check it out.
